[package]
name = "howl_api"
version = "0.1.0"
authors = ["Rodrigo Naranjo <rodnaranjop@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "app"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.2.0"

[dev-dependencies]
reqwest = "0.10.9"
tokio = "0.2.22"
